# Homebrew packages installed on 2026-10-06 (Apple Silicon)

brew "adb-enhanced"
brew "gh"
brew "git"
brew "htop"
brew "nmap"
brew "node@22"
brew "podman"
brew "poppler"
brew "python-tk@3.14"
brew "python@3.11"
brew "rclone"
brew "telnet"
brew "wget"
brew "zsh-completions"
brew "zsh-syntax-highlighting"

cask "android-platform-tools"
cask "google-chrome"
cask "inkscape"
cask "iterm2"
cask "mac-sai"
cask "macfuse"
cask "obsidian"
cask "openinterminal"
cask "raycast"
cask "spotify"
cask "steam"
cask "tor-browser"
